export const Categories = [
    { key: 'editors', title: 'IDEs/Editors' },
    { key: 'version-control', title: 'Version Control' },
    { key: 'collaboration', title: 'Code Collaboration Tools' },
    { key: 'api-testing', title: 'API Development and Testing' },
    { key: 'languages', title: 'Languages' },
    { key: 'frameworks', title: 'Frameworks, Platforms, and Libraries' },
    { key: 'database', title: 'Database Management' },
    { key: 'deployment', title: 'Deployment' },
    { key: 'css-tools', title: 'CSS Frameworks and Tools' },
    { key: 'linting', title: 'Linting and Formatting' },
    { key: 'package-managers', title: 'Package Managers' },
    { key: 'build-tools', title: 'Build Tools' },
    { key: 'monitoring', title: 'Monitoring and Logging' },
    { key: 'documentation', title: 'Documentation Tools' },
    { key: 'markup', title: 'Markup Languages' },
];

export const Skills = [
    { category: 'editors', name: 'Visual Studio', icon: 'SiVisualstudio' },
    { category: 'editors', name: 'Visual Studio Code', icon: 'SiVisualstudiocode' },
    { category: 'version-control', name: 'Git', icon: 'FaGitAlt' },
    { category: 'version-control', name: 'GitHub', icon: 'FaGithub' },
    { category: 'version-control', name: 'GitHub Actions', icon: 'FaGithubAlt' },
    { category: 'version-control', name: 'GitHub Pages', icon: 'SiGithubpages' },
    { category: 'collaboration', name: 'Slack', icon: 'FaSlack' },
    { category: 'collaboration', name: 'Trello', icon: 'FaTrello' },
    { category: 'collaboration', name: 'Figma', icon: 'FaFigma' },
    { category: 'api-testing', name: 'Postman', icon: 'SiPostman' },
    { category: 'languages', name: 'C#', icon: 'SiCsharp' },
    { category: 'languages', name: 'JavaScript', icon: 'IoLogoJavascript' },
    { category: 'languages', name: 'TypeScript', icon: 'SiTypescript' },
    { category: 'languages', name: 'Python', icon: 'FaPython' },
    { category: 'frameworks', name: 'DotnetCore', icon: 'DiDotnet' },
    { category: 'frameworks', name: 'Dotnet', icon: 'AiOutlineDotNet' },
    { category: 'frameworks', name: 'Blazor', icon: 'SiBlazor' },
    { category: 'frameworks', name: 'React', icon: 'FaReact' },
    { category: 'frameworks', name: 'NodeJS', icon: 'FaNode' },
    { category: 'frameworks', name: 'Express', icon: 'SiExpress' },
    { category: 'frameworks', name: 'D3js', icon: 'SiD3Dotjs' },
    { category: 'frameworks', name: 'Django', icon: 'SiDjango' },
    { category: 'database', name: 'MySQL', icon: 'SiMysql' },
    { category: 'database', name: 'Mongo', icon: 'SiMongodb' },
    { category: 'database', name: 'PSQL', icon: 'DiPostgresql' },
    { category: 'deployment', name: 'Azure', icon: 'SiMicrosoftazure' },
    { category: 'deployment', name: 'Netlify', icon: 'BiLogoNetlify' },
    { category: 'deployment', name: 'GitHubPages', icon: 'SiGithubpages' },
    { category: 'css-tools', name: 'CSS', icon: 'FaCss3' },
    { category: 'css-tools', name: 'Tailwind CSS', icon: 'RiTailwindCssFill' },
    { category: 'css-tools', name: 'Material UI', icon: 'SiMui' },
    { category: 'css-tools', name: 'Daisy UI', icon: 'SiDaisyui' },
    { category: 'linting', name: 'ESLint', icon: 'SiEslint' },
    { category: 'package-managers', name: 'NPM', icon: 'FaNpm' },
    { category: 'package-managers', name: 'NuGet', icon: 'SiNuget' },
    { category: 'build-tools', name: 'Webpack', icon: 'SiWebpack' },
    { category: 'build-tools', name: 'Babel', icon: 'SiBabel' },
    { category: 'monitoring', name: 'Serilog', icon: 'SiSerilog' },
    { category: 'api-testing', name: 'Google Maps Platform API', icon: 'SiGooglemaps' },
    { category: 'api-testing', name: 'Google Analytics', icon: 'SiGoogleanalytics' },
    { category: 'api-testing', name: 'FireBase', icon: 'RiFirebaseLine' },
    { category: 'documentation', name: 'Markdown', icon: 'FaMarkdown' },
    { category: 'markup', name: 'HTML', icon: 'FaHtml5' },
];

const SkillsDetails = {
    Categories,
    Skills,
};

export default SkillsDetails;